import type { AppConfig } from '../types'

export const clearlungs: AppConfig = {
  id: 'clearlungs',
  name: 'ClearLungs',
  tagline: 'Quit smoking. Breathe free.',
  description: 'Free private streak tracker for quitting smoking. No account needed.',
  accentColor: '#10b981',
  accentGlow: '#6ee7b7',
  accentDim: '#065f46',
  successColor: '#34d399',
  unitLabel: 'days smoke-free',
  unitLabelSingular: 'day smoke-free',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Detoxing', color: 'text-warning' },
    { maxDay: 14, label: 'Clearing', color: 'text-warning' },
    { maxDay: 30, label: 'Healing', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Restoring', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Renewed', color: 'text-success' },
    { maxDay: Infinity, label: 'Smoke-Free', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First day smoke-free. Within 20 minutes, your heart rate dropped.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Nicotine is out of your body. The chemical addiction is broken.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A8}', message: 'One week. Your lungs are starting to clear. Breathing is easier.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Circulation is improving. Walking and exercise feel easier.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The habit triggers are weakening. You\'re rewriting your routines.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month smoke-free. Lung function is increasing. Coughing decreases.' },
    { day: 45, label: '45 Days', icon: '\u{1FAC1}', message: 'Cilia in your lungs are regrowing. Your body\'s defenses are restoring.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months free. Your risk of heart disease is already dropping.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Three months smoke-free. Lung capacity has improved up to 30%.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'You\'re a non-smoker now. Not someone who\'s quitting — someone who quit.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year. Your cough is gone. Your lungs are deeply healed.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year smoke-free. Your heart disease risk is halved. Incredible.' },
  ],
  quotes: [
    "Every cigarette you don't smoke is a gift to your future self.",
    "Your lungs are already healing. Don't interrupt the process.",
    "The craving lasts 3-5 minutes. The freedom lasts forever.",
    "You didn't fail 20 times. You practiced 20 times.",
    "Smoking doesn't relieve stress. It creates stress and briefly pauses it.",
    "Your children will never remember you smelling like cigarettes.",
    "The money you save could fund your next vacation.",
    "Clean air is the best thing you'll ever breathe.",
    "Every smoke-free hour, your body is repairing damage.",
    "You're not quitting. You're returning to who you were before.",
    "The tobacco industry profits from your addiction. Take your money back.",
    "Your sense of taste and smell are coming alive again.",
    "Nobody ever regretted quitting smoking. Nobody.",
    "The habit feels permanent but your body heals fast.",
    "You can be in the same room as smokers and choose differently.",
    "Running doesn't hurt when your lungs work properly.",
    "The hardest part is the first week. You survived it.",
    "A non-smoker isn't someone who never smoked. It's someone who stopped.",
    "Your heartbeat is stronger without nicotine constricting your vessels.",
    "Every day smoke-free reduces your cancer risk. Every single day.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week smoke-free. Nicotine is out of your system." },
    { maxWeek: 2, message: "Two weeks clean. Your circulation is measurably improving." },
    { maxWeek: 4, message: "Lung cilia are regrowing. Your body's natural defenses are returning." },
    { maxWeek: 8, message: "Lung function is up. Exercise capacity is increasing noticeably." },
    { maxWeek: 12, message: "Three months smoke-free. Your lungs have healed significantly." },
    { maxWeek: Infinity, message: "You're a non-smoker. Your heart disease risk drops more every day." },
  ],
  defaultDailyCost: 10,
  costLabel: 'on cigarettes',
  recoveryTimeline: [
    { day: 0, title: 'Heart Rate Drops', description: 'Within 20 minutes of your last cigarette, heart rate and blood pressure start returning to normal.', icon: '❤️' },
    { day: 1, title: 'Carbon Monoxide Clears', description: 'CO levels in your blood drop to normal. Oxygen delivery to your organs improves immediately.', icon: '🫁' },
    { day: 3, title: 'Nicotine Gone, Senses Return', description: 'All nicotine has left your body. Nerve endings begin regenerating. Taste and smell start improving.', icon: '👃' },
    { day: 14, title: 'Circulation Improving', description: 'Blood flow to lungs and extremities is better. Physical activity becomes easier. Skin tone improves.', icon: '🩸' },
    { day: 30, title: 'Lung Cilia Regrowing', description: 'Your lungs\' cleaning system is restoring itself. Coughing decreases as cilia clear out accumulated tar.', icon: '🌱' },
    { day: 60, title: 'Lung Function Up 30%', description: 'Measurable improvement in lung capacity. Shortness of breath is significantly reduced. Exercise is easier.', icon: '💨' },
    { day: 90, title: 'Immune System Recovered', description: 'White blood cell counts normalize. Your risk of infection has dropped. Cilia are fully regrown.', icon: '🛡️' },
    { day: 365, title: 'Heart Disease Risk Halved', description: 'Your risk of coronary heart disease is now 50% that of a smoker\'s. Your body has profoundly healed.', icon: '❤️‍🩹' },
  ],
  journalPrompts: [
    'What triggered a craving today?',
    'How does your breathing feel compared to when you smoked?',
    'What do you notice about your sense of taste and smell?',
    'How much money have you saved by not buying cigarettes?',
    'What physical activity was easier today than before?',
    'How did you handle a stressful moment without smoking?',
    'What surprised you about being smoke-free?',
    'Who has noticed the positive changes in you?',
  ],
  stripeLink: '',
}
