import type { AppConfig } from '../types'

export const decaf: AppConfig = {
  id: 'decaf',
  name: 'Decaf',
  tagline: 'Find your natural energy.',
  description: 'Free private streak tracker for quitting caffeine. No account needed.',
  accentColor: '#d97706',
  accentGlow: '#fbbf24',
  accentDim: '#92400e',
  successColor: '#34d399',
  unitLabel: 'days caffeine-free',
  unitLabelSingular: 'day caffeine-free',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Detoxing', color: 'text-warning' },
    { maxDay: 14, label: 'Stabilizing', color: 'text-warning' },
    { maxDay: 30, label: 'Resetting', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Balancing', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Natural Energy', color: 'text-success' },
    { maxDay: Infinity, label: 'Caffeine-Free', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First day without caffeine. Headaches are normal — they\'ll pass.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Peak withdrawal. The headache is your brain recalibrating. Stay hydrated.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A1}', message: 'One week free. Withdrawal symptoms are fading. Sleep is improving.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Your adenosine receptors are resetting. Natural tiredness cues return.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The ritual habit is breaking. You don\'t reach for coffee automatically anymore.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month caffeine-free. Your sleep quality has transformed.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Your natural energy rhythm is establishing. No more afternoon crashes.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Steady energy all day. No peaks, no crashes. Just flow.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully reset. You run on your own energy now. No stimulants needed.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'Your baseline energy is higher than it was on caffeine.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of natural energy. Your adrenals have fully recovered.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year caffeine-free. You\'ve proven you never needed it.' },
  ],
  quotes: [
    "Caffeine doesn't give you energy. It borrows it from later.",
    "The headache is temporary. The freedom is permanent.",
    "Your body knows how to make energy. Let it remember.",
    "Coffee culture sold you a dependency disguised as a personality.",
    "Real energy doesn't come in a cup.",
    "You're not tired. You're withdrawing. There's a difference.",
    "Your sleep quality is about to transform.",
    "The afternoon crash disappears when you quit the morning spike.",
    "Anxiety drops when caffeine goes. Coincidence? No.",
    "You don't need a substance to start your day.",
    "Your adrenal glands are healing. Be patient with the process.",
    "Steady energy beats spike-and-crash every time.",
    "The ritual can stay. The caffeine doesn't have to.",
    "Hydration does more for energy than any stimulant.",
    "You're not quitting coffee. You're choosing freedom from dependence.",
    "Your heart rate will thank you. Your blood pressure will thank you.",
    "Natural wakefulness is better than artificial alertness.",
    "The first week is the hardest. You're already in it.",
    "Most people never try. You're doing it.",
    "Your natural circadian rhythm is more powerful than any drug.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week done. Withdrawal headaches should be fading." },
    { maxWeek: 2, message: "Two weeks free. Your sleep architecture is improving." },
    { maxWeek: 4, message: "Adenosine receptors are resetting. Natural energy is returning." },
    { maxWeek: 8, message: "Your cortisol rhythm is normalizing. Steady energy all day." },
    { maxWeek: 12, message: "Three months caffeine-free. Your adrenals are fully recovered." },
    { maxWeek: Infinity, message: "You run on your own energy. No stimulants needed." },
  ],
  defaultDailyCost: 6,
  costLabel: 'on coffee',
}
