import type { AppConfig } from '../types'

export const fasttrack: AppConfig = {
  id: 'fasttrack',
  name: 'FastTrack',
  tagline: 'Master your fasting. Transform your body.',
  description: 'Free private intermittent fasting streak tracker. No account needed.',
  accentColor: '#f59e0b',
  accentGlow: '#fcd34d',
  accentDim: '#b45309',
  successColor: '#34d399',
  unitLabel: 'days fasting',
  unitLabelSingular: 'day fasting',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Adapting', color: 'text-danger' },
    { maxDay: 7, label: 'Adjusting', color: 'text-warning' },
    { maxDay: 14, label: 'Fat-Adapting', color: 'text-warning' },
    { maxDay: 30, label: 'Metabolic Shift', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Autophagy', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Deep Ketosis', color: 'text-success' },
    { maxDay: Infinity, label: 'Metabolically Flexible', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First fast complete. Your insulin levels are already dropping.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Three days in. Your body is learning to access fat stores.' },
    { day: 7, label: '1 Week', icon: '\u{26A1}', message: 'One week of fasting. Hunger hormones are starting to regulate.' },
    { day: 14, label: '2 Weeks', icon: '\u{1F4A1}', message: 'Two weeks consistent. Your metabolism is shifting to fat-burning.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'Fasting feels natural now. Autophagy is cleaning your cells.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month of discipline. Your body composition is changing.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Brain clarity is peaking. Your relationship with food has transformed.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Deep metabolic changes. Your energy levels are more stable than ever.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Metabolically transformed. Fasting is now part of who you are.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'Mastery. Your body runs like a machine now.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of consistent fasting. Incredible discipline.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One full year. You\'ve built an unshakeable lifestyle.' },
  ],
  quotes: [
    "Hunger is not an emergency. It's a signal that your body is working.",
    "The body heals when you stop feeding it constantly.",
    "Fasting is the oldest and most powerful healing method.",
    "You are not starving. You are healing.",
    "Every hour fasted is an hour your body repairs itself.",
    "Discipline is the bridge between your goals and your results.",
    "Your ancestors didn't eat every 3 hours. Neither should you.",
    "The hunger passes. The results stay.",
    "Autophagy: your body's built-in recycling program.",
    "Empty stomach, clear mind.",
    "Fasting doesn't take willpower. It builds it.",
    "Your body has enough fuel stored. Trust it.",
    "The first meal tastes better when you've earned it.",
    "Comfort eating is a trap. Fasting is freedom.",
    "Every fast is an investment in your future health.",
    "Your insulin sensitivity improves with every fasting window.",
    "The longer you fast, the easier it gets.",
    "Your body is more resilient than your mind believes.",
    "Growth hormone surges while you fast. You're getting stronger.",
    "Let hunger remind you of your commitment, not your weakness.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week of fasting complete. Your insulin levels are stabilizing." },
    { maxWeek: 2, message: "Two weeks in. Your hunger hormones are recalibrating." },
    { maxWeek: 4, message: "Your body is becoming efficient at switching between fuel sources." },
    { maxWeek: 8, message: "Deep metabolic changes. Your energy is more stable than ever." },
    { maxWeek: 12, message: "Three months of fasting. Your metabolic flexibility is elite." },
    { maxWeek: Infinity, message: "Fasting is second nature now. You've mastered your metabolism." },
  ],
  recoveryTimeline: [
    { day: 1, title: 'Insulin Drops', description: 'Within 12 hours of fasting, insulin levels drop significantly. Your body begins switching from glucose to stored fat.', icon: '📉' },
    { day: 3, title: 'Fat-Burning Mode', description: 'Your body is accessing fat stores more efficiently. Ketone production is beginning. Hunger hormones start adapting.', icon: '🔥' },
    { day: 7, title: 'Hunger Hormones Regulate', description: 'Ghrelin (hunger hormone) patterns are resetting. You feel hungry at your eating window, not all day.', icon: '🧪' },
    { day: 14, title: 'Fat-Adapted', description: 'Your metabolism can seamlessly switch between glucose and fat. Fasting feels natural, not forced.', icon: '⚡' },
    { day: 30, title: 'Autophagy Patterns', description: 'Regular fasting triggers cellular cleanup. Damaged proteins and organelles are recycled. Your cells are younger.', icon: '🔄' },
    { day: 60, title: 'Metabolic Flexibility', description: 'Your body is metabolically flexible. Energy is stable. Insulin sensitivity is excellent. Body composition has changed.', icon: '💪' },
    { day: 90, title: 'Metabolic Transformation', description: 'Your relationship with food and hunger has fundamentally changed. Your metabolism is optimized for longevity.', icon: '👑' },
  ],
  journalPrompts: [
    'How long did you fast today and how did it feel?',
    'What was your first meal and how satisfying was it?',
    'How was your mental clarity during the fast?',
    'Did you feel hungry? When was it worst?',
    'How is your energy during fasting compared to week 1?',
    'What physical changes have you noticed?',
    'What did you do during your fasting window instead of eating?',
    'How has fasting changed your relationship with food?',
  ],
}
