import type { AppConfig } from '../types'

export const greenday: AppConfig = {
  id: 'greenday',
  name: 'GreenDay',
  tagline: 'Clear your mind. Live sharper.',
  description: 'Free private streak tracker for quitting weed. No account needed.',
  accentColor: '#22c55e',
  accentGlow: '#86efac',
  accentDim: '#15803d',
  successColor: '#34d399',
  unitLabel: 'days sober',
  unitLabelSingular: 'day sober',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Detoxing', color: 'text-warning' },
    { maxDay: 14, label: 'Clearing', color: 'text-warning' },
    { maxDay: 30, label: 'Recovering', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Sharpening', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Resetting', color: 'text-success' },
    { maxDay: Infinity, label: 'Clear', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'Day one. You chose clarity over comfort. That takes courage.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'THC is starting to leave your fat cells. Sleep may be rough — it gets better.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A1}', message: 'One week clean. Your REM sleep is returning. Dreams are back.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Two weeks. Mental fog is lifting. You can think more clearly.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The habit loop is breaking. Cravings are losing their power.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month sober. Your motivation and drive are noticeably stronger.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'THC is mostly cleared. Your memory and focus are sharpening.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months of clarity. Your emotional regulation is restored.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully clear. Your brain has reset. You see the world differently now.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'This is your baseline now. Sharp, present, alive.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year sober. You\'ve built a life that doesn\'t need it.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year clean. You proved to yourself what you\'re capable of.' },
  ],
  quotes: [
    "Clarity is the high you've been chasing.",
    "You're not losing a crutch. You're finding your legs.",
    "The real you is underneath the haze.",
    "Boredom isn't the enemy. It's the beginning of creativity.",
    "You didn't need it before. You don't need it now.",
    "Sobriety isn't boring. Your dopamine system was just broken.",
    "Your dreams came back for a reason. You're healing.",
    "The fog lifts. The ambition returns. Trust the process.",
    "Every sober day, your memory gets a little sharper.",
    "You're choosing the uncomfortable path to a better life.",
    "Weed didn't help your anxiety. It paused it and charged interest.",
    "Present > numb. Every time.",
    "Your real personality is coming back. Let it.",
    "The hardest part is deciding. You already did that.",
    "Discomfort is the price of growth. Pay it gladly.",
    "You're not missing out. You're opting in to real life.",
    "THC numbed the bad. But it also numbed the good.",
    "Sleep gets better. Focus gets better. Everything gets better.",
    "You don't need a substance to be at peace.",
    "Your future self is cheering you on right now.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week done. Your REM sleep is starting to return." },
    { maxWeek: 2, message: "Two weeks sober. Mental clarity is improving day by day." },
    { maxWeek: 4, message: "THC is clearing from your system. Focus is sharpening." },
    { maxWeek: 8, message: "Your brain's reward system is recalibrating. Motivation is rising." },
    { maxWeek: 12, message: "Three months clear. You've broken the psychological dependence." },
    { maxWeek: Infinity, message: "You've proven this is permanent. Clarity is your default now." },
  ],
  defaultDailyCost: 12,
  costLabel: 'on weed',
  recoveryTimeline: [
    { day: 1, title: 'THC Begins Leaving', description: 'Your body starts metabolizing stored THC from fat cells. Irritability, loss of appetite, and restlessness are common.', icon: '🧪' },
    { day: 3, title: 'Withdrawal Peaks', description: 'Irritability, insomnia, and night sweats are at their worst. Your endocannabinoid system is recalibrating.', icon: '🔥' },
    { day: 7, title: 'REM Sleep Returns', description: 'Vivid dreams come back — sometimes intensely. This is your brain catching up on suppressed REM sleep.', icon: '😴' },
    { day: 14, title: 'Mental Fog Lifting', description: 'Short-term memory and focus are improving. Your brain is clearing the haze that THC maintained.', icon: '💡' },
    { day: 30, title: 'Appetite Normalizes', description: 'Hunger cues reset to natural levels. Emotional eating patterns are breaking. Motivation increases.', icon: '🍎' },
    { day: 45, title: 'THC Mostly Cleared', description: 'Most THC metabolites have left your fat cells. Memory recall and processing speed are noticeably sharper.', icon: '🧠' },
    { day: 60, title: 'Emotional Regulation Restored', description: 'Without THC blunting emotions, you feel the full range again. Coping skills are strengthening naturally.', icon: '💫' },
    { day: 90, title: 'Full Cognitive Recovery', description: 'Your brain has substantially recovered. Focus, motivation, and memory are at their natural baseline.', icon: '👑' },
  ],
  journalPrompts: [
    'What did you do when boredom hit today?',
    'How was your sleep and did you have vivid dreams?',
    'What emotions came up that weed used to dull?',
    'What creative or productive thing did you do today?',
    'How is your appetite and relationship with food?',
    'What clarity or insight did you gain today?',
    'What hobby or activity replaced smoking?',
    'How does sober socializing compare to high socializing?',
  ],
  stripeLink: '',
}
