import type { AppConfig } from '../types'

export const iceplunge: AppConfig = {
  id: 'iceplunge',
  name: 'IcePlunge',
  tagline: 'Embrace the cold. Build resilience.',
  description: 'Free private streak tracker for cold plunge and cold exposure habits. No account needed.',
  accentColor: '#3b82f6',
  accentGlow: '#93c5fd',
  accentDim: '#1e40af',
  successColor: '#34d399',
  unitLabel: 'days plunging',
  unitLabelSingular: 'day plunging',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Shocking', color: 'text-danger' },
    { maxDay: 7, label: 'Adapting', color: 'text-warning' },
    { maxDay: 14, label: 'Building', color: 'text-warning' },
    { maxDay: 30, label: 'Hardening', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Resilient', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Ice-Forged', color: 'text-success' },
    { maxDay: Infinity, label: 'Unbreakable', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First plunge done. You did what most people never will.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Three days of cold. Your norepinephrine is spiking — natural energy.' },
    { day: 7, label: '1 Week', icon: '\u{2744}\u{FE0F}', message: 'One week of cold exposure. Your cold shock response is adapting.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Two weeks. Brown fat is activating. Your body thermoregulates better.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The cold feels different now. Your mind is stronger than the water.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month of daily cold. Your dopamine baseline is elevated.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Deep adaptation. Recovery is faster. Inflammation is lower.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months ice-forged. The cold is your ally now.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully adapted. You\'ve built an unshakeable mind and body.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'The cold is easy now. What else can you conquer?' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of cold exposure. Your resilience is extraordinary.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One full year. You are truly ice-forged.' },
  ],
  quotes: [
    "The cold doesn't get easier. You get stronger.",
    "If you can control your breath in ice water, you can control anything.",
    "Comfort is the enemy of growth.",
    "3 minutes of cold. 14 hours of elevated mood.",
    "Your ancestors survived ice ages. This is in your DNA.",
    "The gasp is the gateway. Breathe through it.",
    "Cold exposure is a conversation between your mind and your body.",
    "Dopamine increases 250% after cold exposure. No drug does that safely.",
    "The resistance you feel before getting in is the thing you need to overcome.",
    "Every plunge is a vote for the person you want to become.",
    "Cold water doesn't care about your excuses.",
    "The shower knob is the simplest test of discipline that exists.",
    "You're not just building cold tolerance. You're building life tolerance.",
    "The afterglow is the reward. Chase that feeling.",
    "Inflammation drops. Recovery speeds up. Mood elevates. All from cold water.",
    "The hardest part is always the first 30 seconds.",
    "Your nervous system is being trained for calm under pressure.",
    "Wim Hof was right. The cold is your warm friend.",
    "Mental toughness isn't born. It's built. One plunge at a time.",
    "Get comfortable being uncomfortable.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week of cold exposure. Norepinephrine is already elevated." },
    { maxWeek: 2, message: "Two weeks. Your cold shock response is diminishing — you're adapting." },
    { maxWeek: 4, message: "Brown fat is activating. Your thermoregulation is improving." },
    { maxWeek: 8, message: "Your inflammation markers are lower. Recovery is faster." },
    { maxWeek: 12, message: "Three months ice-forged. Your baseline dopamine is permanently elevated." },
    { maxWeek: Infinity, message: "The cold is second nature. Your resilience is extraordinary." },
  ],
  recoveryTimeline: [
    { day: 1, title: 'Norepinephrine Surge', description: 'Cold exposure triggers a 200-300% increase in norepinephrine. You feel alert, focused, and energized.', icon: '⚡' },
    { day: 3, title: 'Cold Shock Adapting', description: 'Your cold shock response is beginning to diminish. The gasp reflex weakens. You can breathe more calmly.', icon: '🌊' },
    { day: 7, title: 'Brown Fat Activating', description: 'Your body is producing more brown adipose tissue. This metabolically active fat burns calories to generate heat.', icon: '🔥' },
    { day: 14, title: 'Thermoregulation Improving', description: 'Your body maintains core temperature more efficiently. You feel less cold in everyday situations.', icon: '🌡️' },
    { day: 30, title: 'Dopamine Baseline Elevated', description: 'Consistent cold exposure has raised your baseline dopamine level. Mood, motivation, and focus are sustainably higher.', icon: '🧠' },
    { day: 60, title: 'Inflammation Markers Lower', description: 'Chronic inflammation is reduced. Recovery from exercise is faster. Joint stiffness and muscle soreness decrease.', icon: '🛡️' },
    { day: 90, title: 'Full Cold Adaptation', description: 'Your cardiovascular system, immune function, and mental resilience have been transformed by consistent cold exposure.', icon: '👑' },
  ],
  journalPrompts: [
    'How long was your cold exposure today?',
    'What was the water temperature?',
    'How did you feel in the first 30 seconds vs the last 30?',
    'Rate your mental resistance before getting in (1-10).',
    'How was your mood and energy after the plunge?',
    'Did you practice breath control during the cold?',
    'What was hardest — the anticipation or the cold itself?',
    'How has cold exposure affected other areas of your life?',
  ],
  stripeLink: '',
}
