import type { AppConfig } from '../types'

export const primal: AppConfig = {
  id: 'primal',
  name: 'Primal',
  tagline: 'Optimize your testosterone. Naturally.',
  description: 'Free private streak tracker for testosterone-boosting habits. No account needed.',
  accentColor: '#ef4444',
  accentGlow: '#fca5a5',
  accentDim: '#991b1b',
  successColor: '#34d399',
  unitLabel: 'days optimizing',
  unitLabelSingular: 'day optimizing',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Starting', color: 'text-danger' },
    { maxDay: 7, label: 'Building', color: 'text-warning' },
    { maxDay: 14, label: 'Adapting', color: 'text-warning' },
    { maxDay: 30, label: 'Optimizing', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Elevating', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Peak', color: 'text-success' },
    { maxDay: Infinity, label: 'Primal', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'Day one of optimizing. Every small change compounds.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Three days of better habits. Your body is listening.' },
    { day: 7, label: '1 Week', icon: '\u{26A1}', message: 'One week consistent. Sleep quality is the first thing to improve.' },
    { day: 14, label: '2 Weeks', icon: '\u{1F4A1}', message: 'Two weeks in. Testosterone peaks during consistent sleep and exercise.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'Three weeks of discipline. Your body is adapting to the new baseline.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month strong. Strength, confidence, and drive are all rising.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Deep hormonal shifts. Your body composition is visibly changing.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months of consistency. Your hormonal profile is optimized.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully optimized. You\'re operating at a different level now.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'This isn\'t a phase. This is your new operating system.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of optimization. The compound effects are massive.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year of primal living. You\'re a different person now.' },
  ],
  quotes: [
    "Your hormones respond to your habits. Choose wisely.",
    "Sleep is the most anabolic thing you can do.",
    "Lift heavy. Sleep deep. Eat clean. Repeat.",
    "Sunlight, cold exposure, and heavy compound lifts. The trifecta.",
    "Your testosterone is a reflection of your lifestyle.",
    "The gym is where you build. Sleep is where you grow.",
    "Eliminate the things that lower T before adding things that raise it.",
    "Stress management isn't soft. It's hormonal optimization.",
    "Your grandfather had higher T by default. Earn yours back.",
    "Consistency beats intensity. Show up every day.",
    "Cold showers aren't punishment. They're training.",
    "Processed food is an anti-testosterone weapon. Eat real food.",
    "Your body wants to produce testosterone. Stop sabotaging it.",
    "Discipline in one area bleeds into every other area of life.",
    "The men who optimize their health optimize their lives.",
    "Morning sunlight sets your circadian rhythm. Free testosterone boost.",
    "Every rep, every clean meal, every hour of sleep compounds.",
    "Your energy, confidence, and drive are all downstream of your hormones.",
    "Stop accepting low energy as normal. It's not.",
    "The best supplement is consistent sleep, exercise, and real food.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week of optimizing. Sleep quality is the foundation." },
    { maxWeek: 2, message: "Two weeks consistent. Your body is responding to the new inputs." },
    { maxWeek: 4, message: "Hormonal pathways are adapting. Strength and energy are rising." },
    { maxWeek: 8, message: "Deep changes. Your body composition and mood are shifting." },
    { maxWeek: 12, message: "Three months of optimization. You're operating at a new level." },
    { maxWeek: Infinity, message: "This is your lifestyle now. Primal optimization is who you are." },
  ],
}
