import type { AppConfig } from '../types'

export const rewire: AppConfig = {
  id: 'rewire',
  name: 'Rewire',
  tagline: 'Break free. Rewire your brain.',
  description: 'Free private streak tracker for quitting porn and rewiring your brain.',
  accentColor: '#7c6bf5',
  accentGlow: '#b4a8ff',
  accentDim: '#4a3d8f',
  successColor: '#34d399',
  unitLabel: 'days clean',
  unitLabelSingular: 'day clean',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Adjusting', color: 'text-warning' },
    { maxDay: 14, label: 'Recovering', color: 'text-warning' },
    { maxDay: 30, label: 'Resetting', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Strengthening', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Rewiring', color: 'text-success' },
    { maxDay: Infinity, label: 'Rewired', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'You took the first step. The hardest part is deciding to change.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'You survived the withdrawal peak. It gets easier from here.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A1}', message: 'One full week. Your brain clarity is already improving.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Dopamine receptors are resetting. You feel things more deeply now.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The old habit is breaking. New neural pathways are solidifying.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month strong. Your confidence and energy are transformed.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Deep prefrontal cortex changes. Your willpower is stronger than ever.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'This is your new normal. The old you feels like a distant memory.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully rewired. Your brain has fundamentally changed. You did it.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'Mastery. You\'ve proven this isn\'t temporary — it\'s who you are.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of freedom. You are truly transformed.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'Legendary. One full year. You are an absolute inspiration.' },
  ],
  quotes: [
    "Your future self is watching you right now through memories.",
    "Discipline is choosing between what you want now and what you want most.",
    "The pain of discipline weighs ounces. The pain of regret weighs tons.",
    "You don't have to be extreme. Just consistent.",
    "Small daily improvements are the key to staggering long-term results.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Freedom is what you do with what's been done to you.",
    "A year from now you'll wish you had started today.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are not your urges. You are the one who decides.",
    "Every day you resist, your brain rewires a little more.",
    "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.",
    "The chains of habit are too light to be felt until they are too heavy to be broken.",
    "You will never always be motivated. You have to learn to be disciplined.",
    "What you resist persists. What you accept transforms.",
    "Your brain is plastic. It can literally reshape itself. Let it.",
    "One day or day one. You decide.",
    "It's not about being perfect. It's about being better than yesterday.",
    "The urge will pass whether you give in or not.",
    "You're not starting over. You're starting from experience.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First full week complete. Your dopamine system is already adjusting." },
    { maxWeek: 2, message: "Two weeks strong. Brain fog is lifting and energy is rising." },
    { maxWeek: 4, message: "Your neural pathways are actively reshaping. Stay consistent." },
    { maxWeek: 8, message: "You're in deep recovery mode. The changes are becoming permanent." },
    { maxWeek: 12, message: "Three months of rewiring. You've fundamentally changed." },
    { maxWeek: Infinity, message: "You're in elite territory. Very few make it this far." },
  ],
  recoveryTimeline: [
    { day: 1, title: 'Dopamine Reset Begins', description: 'Your brain stops receiving artificial dopamine surges. Withdrawal symptoms like restlessness and anxiety are normal.', icon: '🧪' },
    { day: 3, title: 'Withdrawal Peak', description: 'Urges are strongest now. Your brain is demanding the dopamine it\'s used to. This is the hardest part — it gets easier.', icon: '🔥' },
    { day: 7, title: 'Sleep Improves', description: 'Without late-night stimulation, your circadian rhythm is resetting. Deeper sleep means better recovery.', icon: '😴' },
    { day: 14, title: 'Dopamine Receptors Healing', description: 'Your D2 dopamine receptors are upregulating. You start finding joy in everyday things again.', icon: '🧠' },
    { day: 30, title: 'Prefrontal Cortex Strengthening', description: 'The decision-making center of your brain is regaining control over impulses. Willpower feels easier.', icon: '💪' },
    { day: 45, title: 'Emotional Depth Returns', description: 'Numbed emotions come back online. You feel things more deeply — both good and challenging.', icon: '💫' },
    { day: 60, title: 'Neural Pathways Rewiring', description: 'Old habit circuits are weakening. New healthy patterns are solidifying in your brain.', icon: '🔄' },
    { day: 90, title: 'Brain Fully Rewired', description: 'Your prefrontal cortex has regained full executive control. The addiction pathway has been significantly weakened.', icon: '👑' },
  ],
  journalPrompts: [
    'What triggered an urge today and how did you handle it?',
    'What positive changes have you noticed since starting?',
    'How is your energy and focus compared to before?',
    'What activities replaced the old habit today?',
    'How are your social interactions and confidence?',
    'What are you grateful for in your recovery?',
    'Describe a moment today where you felt genuinely proud.',
    'What would you tell someone on Day 1?',
  ],
}
