import type { AppConfig } from '../types'

export const sober: AppConfig = {
  id: 'sober',
  name: 'Sober',
  tagline: 'Choose clarity. Every single day.',
  description: 'Free private sobriety tracker for quitting alcohol. No account needed.',
  accentColor: '#6366f1',
  accentGlow: '#a5b4fc',
  accentDim: '#3730a3',
  successColor: '#34d399',
  unitLabel: 'days sober',
  unitLabelSingular: 'day sober',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Detox', color: 'text-danger' },
    { maxDay: 7, label: 'Stabilizing', color: 'text-warning' },
    { maxDay: 14, label: 'Clearing', color: 'text-warning' },
    { maxDay: 30, label: 'Healing', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Recovering', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Renewing', color: 'text-success' },
    { maxDay: Infinity, label: 'Sober', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'Day one of sobriety. The bravest thing you can do is start.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Three days sober. Your liver is already beginning to repair.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A1}', message: 'One week. Sleep quality is improving. You\'re thinking clearer.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Two weeks. Your blood pressure is normalizing. Skin is clearing.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The drinking habit is breaking. Social triggers are getting easier.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month sober. Liver fat can reduce up to 20%. You\'re healing.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Brain fog is gone. Your memory and focus are sharper than ever.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months clean. Your emotional stability has transformed.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Three months sober. Your brain and body are profoundly healed.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'You\'ve proven sobriety isn\'t a phase. It\'s a choice you make daily.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of clarity. Your relationships and health are transformed.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year sober. You are living proof that change is possible.' },
  ],
  quotes: [
    "Sobriety isn't giving up drinking. It's gaining everything else.",
    "The hangover you don't have is the best feeling in the world.",
    "You never regret a night you stayed sober.",
    "Alcohol borrows happiness from tomorrow.",
    "Your best stories don't need alcohol in them.",
    "Clear mornings are worth more than any night out.",
    "The drink promises connection and delivers isolation.",
    "You're not missing out. You're finally showing up.",
    "Sobriety is the ultimate act of self-respect.",
    "The social pressure fades. Your strength doesn't.",
    "Your liver is healing. Your brain is healing. You are healing.",
    "One day at a time isn't a cliche. It's the strategy.",
    "Sober sleep is the best sleep you'll ever have.",
    "Alcohol didn't make things fun. It made you numb to boredom.",
    "The real you is better than the drunk you. Always.",
    "Your anxiety didn't need a drink. The drink caused the anxiety.",
    "Freedom from alcohol is freedom to be fully alive.",
    "Every sober day proves you're stronger than the craving.",
    "You chose the harder path. That's what makes it worth it.",
    "Morning coffee hits different when there's no hangover.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week sober. Your liver is already beginning to repair." },
    { maxWeek: 2, message: "Two weeks clean. Sleep quality and skin are improving." },
    { maxWeek: 4, message: "Your brain chemistry is stabilizing. Mood swings are easing." },
    { maxWeek: 8, message: "Liver fat is reducing. Blood pressure is normalizing." },
    { maxWeek: 12, message: "Three months sober. Your brain has physically healed." },
    { maxWeek: Infinity, message: "You've chosen a sober life. Your health and clarity prove it." },
  ],
}
