import type { AppConfig } from '../types'

export const sugarfree: AppConfig = {
  id: 'sugarfree',
  name: 'SugarFree',
  tagline: 'Break the sugar cycle. Feel alive.',
  description: 'Free private streak tracker for quitting sugar. No account needed.',
  accentColor: '#ec4899',
  accentGlow: '#f9a8d4',
  accentDim: '#9d174d',
  successColor: '#34d399',
  unitLabel: 'days sugar-free',
  unitLabelSingular: 'day sugar-free',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Detoxing', color: 'text-warning' },
    { maxDay: 14, label: 'Resensitizing', color: 'text-warning' },
    { maxDay: 30, label: 'Stabilizing', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Healing', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Renewed', color: 'text-success' },
    { maxDay: Infinity, label: 'Sugar-Free', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First day without sugar. The cravings will peak soon — you\'re ready.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Peak withdrawal is here. Headaches and irritability are normal. Push through.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A1}', message: 'One week. Your blood sugar is stabilizing. Energy crashes are fading.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Your taste buds are resensitizing. Real food tastes amazing now.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The sugar habit loop is breaking. Cravings are much weaker.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month sugar-free. Your skin is clearer and energy is stable.' },
    { day: 45, label: '45 Days', icon: '\u{1F9E0}', message: 'Your gut microbiome is healing. Inflammation is dropping.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Sugar cravings feel distant now. Your body runs on real fuel.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully reset. Your relationship with food is transformed.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'Sugar doesn\'t even tempt you anymore. This is freedom.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year sugar-free. Your health markers have transformed.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One year without sugar. You\'ve beaten one of the hardest addictions.' },
  ],
  quotes: [
    "Sugar is the most socially acceptable addiction on earth.",
    "Your body doesn't need sugar. Your brain is lying to you.",
    "Every craving is your old programming fighting change.",
    "The sweetest victory is the one over yourself.",
    "Sugar gave you energy crashes. Freedom gives you stable power.",
    "Your taste buds adapt. Real food will taste incredible again.",
    "The industry spent billions making you addicted. Take your power back.",
    "Inflammation drops. Skin clears. Energy stabilizes. Keep going.",
    "You're not depriving yourself. You're freeing yourself.",
    "The craving lasts minutes. The regret lasts hours.",
    "Your gut bacteria are cheering for you right now.",
    "Sugar is not a reward. It's a trap disguised as one.",
    "Stable blood sugar = stable mood = stable life.",
    "Every sugar-free meal is a vote for the person you want to be.",
    "The withdrawal proves how powerful the addiction was.",
    "You don't need dessert to celebrate. You ARE the celebration.",
    "Your future self's health depends on today's choices.",
    "Real energy comes from real food, not sugar spikes.",
    "The less sugar you eat, the less you want. Trust the process.",
    "Breaking free from sugar is one of the hardest things you can do. You're doing it.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week done. Blood sugar is stabilizing. Energy is evening out." },
    { maxWeek: 2, message: "Two weeks sugar-free. Your taste buds are resensitizing." },
    { maxWeek: 4, message: "Your gut microbiome is shifting. Sugar cravings are fading." },
    { maxWeek: 8, message: "Inflammation markers are dropping. Your body is healing." },
    { maxWeek: 12, message: "Three months free. Your metabolic health has fundamentally improved." },
    { maxWeek: Infinity, message: "Sugar-free is your lifestyle now. You've beaten the sweetest trap." },
  ],
  defaultDailyCost: 5,
  costLabel: 'on sugary foods',
  recoveryTimeline: [
    { day: 1, title: 'Blood Sugar Roller Coaster', description: 'Without constant sugar, your blood glucose swings. Headaches, irritability, and fatigue are your body adjusting.', icon: '🎢' },
    { day: 3, title: 'Sugar Flu Peaks', description: 'Withdrawal symptoms peak — headache, brain fog, and intense cravings. Your body is switching fuel sources.', icon: '🤒' },
    { day: 7, title: 'Blood Sugar Stabilizes', description: 'Insulin sensitivity is improving. Energy crashes are fading. Your body is learning to burn steady fuel.', icon: '⚡' },
    { day: 14, title: 'Taste Buds Resensitize', description: 'Your palate is recalibrating. Fruits taste sweeter. Real food flavors are more vivid and satisfying.', icon: '👅' },
    { day: 30, title: 'Skin Clearing Up', description: 'Reduced glycation means less inflammation. Skin is clearer, less puffy, and more radiant.', icon: '✨' },
    { day: 45, title: 'Gut Microbiome Shifting', description: 'Sugar-loving bacteria are dying off. Anti-inflammatory bacteria are flourishing. Digestion improves.', icon: '🦠' },
    { day: 60, title: 'Inflammation Dropping', description: 'Chronic inflammation markers are significantly reduced. Joint pain, bloating, and brain fog are gone.', icon: '🛡️' },
    { day: 90, title: 'Metabolic Reset Complete', description: 'Your insulin sensitivity, energy levels, and relationship with food are fundamentally transformed.', icon: '👑' },
  ],
  journalPrompts: [
    'What craving hit hardest today and how did you handle it?',
    'What naturally sweet food did you enjoy instead?',
    'How is your energy level throughout the day?',
    'Did you spot hidden sugar in any food labels today?',
    'How is your skin looking compared to before?',
    'What meal did you cook or prepare that was satisfying without sugar?',
    'How do your moods compare to when you ate sugar regularly?',
    'What\'s the biggest change you\'ve noticed so far?',
  ],
  stripeLink: '',
}
