import type { AppConfig } from '../types'

export const vapefree: AppConfig = {
  id: 'vapefree',
  name: 'VapeFree',
  tagline: 'Ditch the vape. Reclaim your lungs.',
  description: 'Free private streak tracker for quitting vaping. No account needed.',
  accentColor: '#06b6d4',
  accentGlow: '#67e8f9',
  accentDim: '#0e7490',
  successColor: '#34d399',
  unitLabel: 'days vape-free',
  unitLabelSingular: 'day vape-free',
  goalDays: 90,
  phases: [
    { maxDay: 3, label: 'Withdrawal', color: 'text-danger' },
    { maxDay: 7, label: 'Detoxing', color: 'text-warning' },
    { maxDay: 14, label: 'Clearing', color: 'text-warning' },
    { maxDay: 30, label: 'Healing', color: 'text-accent-glow' },
    { maxDay: 60, label: 'Restoring', color: 'text-accent-glow' },
    { maxDay: 90, label: 'Renewing', color: 'text-success' },
    { maxDay: Infinity, label: 'Free', color: 'text-success' },
  ],
  milestones: [
    { day: 1, label: 'Day 1', icon: '\u{1F331}', message: 'First day without nicotine. Your body is already starting to heal.' },
    { day: 3, label: 'Day 3', icon: '\u{1F525}', message: 'Nicotine is leaving your system. The worst cravings are behind you.' },
    { day: 7, label: '1 Week', icon: '\u{1F4A8}', message: 'One week free. Your lungs are starting to clear out.' },
    { day: 14, label: '2 Weeks', icon: '\u{26A1}', message: 'Circulation is improving. You can breathe deeper now.' },
    { day: 21, label: '3 Weeks', icon: '\u{1F513}', message: 'The habit loop is breaking. Cravings are getting weaker.' },
    { day: 30, label: '1 Month', icon: '\u{1F4AA}', message: 'One month vape-free. Your lung capacity is noticeably better.' },
    { day: 45, label: '45 Days', icon: '\u{1FAC1}', message: 'Taste and smell are sharper. Your body is thanking you.' },
    { day: 60, label: '2 Months', icon: '\u{1F30A}', message: 'Two months clean. The urge to vape feels foreign now.' },
    { day: 90, label: '90 Days', icon: '\u{1F451}', message: 'Fully free. Your lungs have significantly healed. You did it.' },
    { day: 120, label: '4 Months', icon: '\u{1F3D4}\u{FE0F}', message: 'This is who you are now. A non-vaper.' },
    { day: 180, label: '6 Months', icon: '\u{1F985}', message: 'Half a year of clean air. Your cardiovascular health is transformed.' },
    { day: 365, label: '1 Year', icon: '\u{1F3C6}', message: 'One full year vape-free. Your lungs are almost fully healed.' },
  ],
  quotes: [
    "Your lungs are healing with every breath you don't vape.",
    "The craving lasts 3 minutes. The regret lasts all day.",
    "You're not giving up something. You're gaining everything.",
    "Every puff you don't take is a victory.",
    "Nicotine promised you stress relief but gave you stress.",
    "Your body wants to heal. Just let it.",
    "The vape doesn't relax you. It relieves the withdrawal it caused.",
    "Freedom tastes better than any flavor pod.",
    "You survived 100% of your worst cravings so far.",
    "The best version of you doesn't need nicotine.",
    "Breathe deep. That's what clean lungs feel like.",
    "You're not quitting. You're upgrading.",
    "The money you save is just a bonus. The health is the prize.",
    "Every craving you beat makes the next one weaker.",
    "Your future self will thank you for today.",
    "Addiction told you that you needed it. You proved it wrong.",
    "Clean air. Clear mind. Full lungs.",
    "The discomfort is temporary. The freedom is permanent.",
    "You chose yourself over a chemical.",
    "One day at a time. That's all it takes.",
  ],
  weeklyMessages: [
    { maxWeek: 1, message: "First week done. Nicotine is out of your system now." },
    { maxWeek: 2, message: "Two weeks free. Your circulation is already improving." },
    { maxWeek: 4, message: "Your lung cilia are regrowing. Breathing gets easier every day." },
    { maxWeek: 8, message: "Two months in. Your risk of respiratory infection is dropping." },
    { maxWeek: 12, message: "Three months clean. Your lung function has significantly improved." },
    { maxWeek: Infinity, message: "You've broken free from nicotine. This is your life now." },
  ],
  defaultDailyCost: 8,
  costLabel: 'on vaping',
}
